name: Build and lint Backend
on:
  push:
    branches: main

defaults:
  run:
    shell: bash
    working-directory: ./backend

jobs:
    linting:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
          - name: Check out Git repository
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v1
            with:
              node-version: 22

          - name: Install Node.js dependencies
            run: yarn --frozen-lockfile

          - name: Run linters
            uses: wearerequired/lint-action@v2
            with:
              #eslint: true
              #eslint_dir: backend/
              prettier: true
              prettier_dir: backend/
              auto_fix: true